/* AUTO-GENERATED by scripts/gen-msw-handlers.ts — do not edit */

import type { RequestHandler } from "msw";
import * as _idx from "./../generated/index.msw";
import * as m0 from "./../generated/quiz-management/quiz-management.msw";
import * as m1 from "./../generated/search-discovery/search-discovery.msw";

const _mods = [_idx, m0, m1];

function _toArray<T>(v: T): T[] {
  return Array.isArray(v) ? v : [v];
}

export const handlers: RequestHandler[] = _mods
  .flatMap((mod: Record<string, unknown>) => {
    // biome-ignore lint/suspicious/noExplicitAny: Ignore
    const h = (mod as any).handlers;
    if (Array.isArray(h)) return h;
    // それ以外の export に配列があればそれも展開（orvalの各 msw モジュール事情に合わせた保険）
    return Object.values(mod).filter(Array.isArray).flat() as unknown[];
  })
  // 念のため型ナロー（実質的には cast）
  .filter(Boolean) as RequestHandler[];
